### PR TITLE
Corrected a minor typo to README.md file

### PR DESCRIPTION
**Pull request by joyvuu-dave**
Added a colon after 'edit' on line 24

### CODE REVIEW

**Comment by GothAck** [comment]
Wow, thanks, didn't think anyone was watching that closely... Need to document new updates from today soon too :)

**Comment by joyvuu-dave** [comment]
Just discovered this repo yesterday. Seems like a really good idea.  

## 

Dave Riddle
Joyvuu
(510) 854-6221

**Comment by GothAck** [comment]
Thanks, needs a lot of work though, feel free to open issues if you find anything that you don't get / could be made easier... I will endeavour to update the documentation as soon as I can :)

**Comment by joyvuu-dave** [comment]
Sounds good, will do!

## 

Dave Riddle
Joyvuu
(510) 854-6221

**Pull request merged**
